# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/language-java/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/python:3.12.1

    working_directory: ~/circle-ci

    steps:
      - checkout

      - run: python --version

      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Linting
          command: |
            . venv/bin/activate
            ruff check .

      # Run tests
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python Test.py

